//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceResults
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Turler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turler()
        {
            this.Sonuclar = new HashSet<Sonuclar>();
        }

        [DataMember]
        public int turId { get; set; }
        [DataMember]
        public string turAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sonuclar> Sonuclar { get; set; }
    }
}
